apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://googlecloudplatform.github.io/spark-on-k8s-operator
    chart: spark-operator
    targetRevision: 1.1.27
    helm:
      values: |
        webhook:
          enable: true
        sparkJobNamespace: "spark"
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-connect-server
  namespace: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-connect
  template:
    metadata:
      labels:
        app: spark-connect
    spec:
      containers:
      - name: spark-connect
        image: <your-dockerhub-username>/spark-connect:3.5.1
        ports:
        - containerPort: 15002
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-connect-service
  namespace: spark-operator
spec:
  selector:
    app: spark-connect
  ports:
  - port: 15002
    targetPort: 15002
  type: ClusterIP
