apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.13.1
    helm:
      values: |
        executor: KubernetesExecutor
        defaultAirflowRepository: apache/airflow
        defaultAirflowTag: "2.9.1"

        pgbouncer:
          enabled: true

        data:
          metadataConnection:
            user: postgres
            pass: airflow
            host: airflow-pgbouncer
            port: 6432

        postgresql:
          enabled: true
          auth:
            username: postgres
            password: airflow
            database: airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
